const sentences = [
    "The sun sets behind the mountains.",
    "She quickly grabbed her coat and left.",
    "A cat slept peacefully on the sofa.",
    "We walked along the sandy beach.",
    "The stars shone brightly in the sky.",
    "His coffee was too hot to drink.",
    "They waited patiently for the bus.",
    "The clock ticked loudly in the room.",
    "She whispered a secret to her friend.",
    "A strong wind knocked over the chair.",
    "The old book had yellowed pages.",
    "He played the piano with great skill.",
    "Lightning flashed across the dark sky.",
    "The dog barked at the passing car.",
    "We explored the forest at dawn.",
    "The ice cream melted in the heat.",
    "A baby bird chirped for its mother.",
    "They built a sandcastle near the shore.",
    "Her laughter echoed through the hallway.",
    "He carefully placed the vase on the shelf.",
    "The radio played an old familiar song.",
    "She found a key under the rug.",
    "His shoes were covered in thick mud.",
    "The baker made fresh bread this morning.",
    "A rainbow appeared after the heavy rain.",
    "She packed her bags for the trip.",
    "The fire crackled in the quiet night.",
    "A butterfly landed on his hand.",
    "They cheered loudly for their favorite team.",
    "The librarian arranged books on the shelf.",
    "The bird perched on the window sill.",
    "He solved the puzzle in record time.",
    "She planted flowers in the backyard garden.",
    "The movie started late due to rain.",
    "A mysterious letter arrived in the mail.",
    "They danced under the glowing streetlights.",
    "The chef prepared a delicious Italian meal.",
    "She held the kitten close to her.",
    "A ship sailed across the calm sea.",
    "The computer screen flickered and went dark.",
    "He tied his shoelaces and ran outside.",
    "The detective searched for more hidden clues.",
    "She wrote a poem in her journal.",
    "The car engine roared to life quickly.",
    "They played chess by the cozy fireplace.",
    "The museum displayed ancient Egyptian artifacts.",
    "A fox darted through the thick bushes.",
    "She hummed a song while making tea.",
    "The wind carried away his red hat.",
    "The bridge swayed slightly in the storm."
  ];
  
  export default sentences;